export const TYPES = {
  FETCH_PEOPLE: {
    REQUEST: "FETCH_PEOPLE_REQUEST",
    START: "FETCH_PEOPLE_START",
    SUCCESS: "FETCH_PEOPLE_SUCCESS",
    EROR: "FETCH_PEOPLE_EROR",
  },
  FILTERS: {
    FIRST_NAME: "FILTERS_FIRST_NAME",
    LAST_NAME: "FILTERS_LAST_NAME",
    SEX: {
      MALE: "FILTERS_SEX_MALE",
      FEMALE: "FILTERS_SEX_FEMALE",
    },
    AGE: "FILTERS_AGE",
  },
};
